// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: likes/likes.proto

package likes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Likes_CreateLikes_FullMethodName = "/Likes/CreateLikes"
	Likes_GetLikes_FullMethodName    = "/Likes/GetLikes"
)

// LikesClient is the client API for Likes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikesClient interface {
	CreateLikes(ctx context.Context, in *LikesRequest, opts ...grpc.CallOption) (*LikesResponse, error)
	GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error)
}

type likesClient struct {
	cc grpc.ClientConnInterface
}

func NewLikesClient(cc grpc.ClientConnInterface) LikesClient {
	return &likesClient{cc}
}

func (c *likesClient) CreateLikes(ctx context.Context, in *LikesRequest, opts ...grpc.CallOption) (*LikesResponse, error) {
	out := new(LikesResponse)
	err := c.cc.Invoke(ctx, Likes_CreateLikes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likesClient) GetLikes(ctx context.Context, in *GetLikesRequest, opts ...grpc.CallOption) (*GetLikesResponse, error) {
	out := new(GetLikesResponse)
	err := c.cc.Invoke(ctx, Likes_GetLikes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikesServer is the server API for Likes service.
// All implementations must embed UnimplementedLikesServer
// for forward compatibility
type LikesServer interface {
	CreateLikes(context.Context, *LikesRequest) (*LikesResponse, error)
	GetLikes(context.Context, *GetLikesRequest) (*GetLikesResponse, error)
	mustEmbedUnimplementedLikesServer()
}

// UnimplementedLikesServer must be embedded to have forward compatible implementations.
type UnimplementedLikesServer struct {
}

func (UnimplementedLikesServer) CreateLikes(context.Context, *LikesRequest) (*LikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLikes not implemented")
}
func (UnimplementedLikesServer) GetLikes(context.Context, *GetLikesRequest) (*GetLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikes not implemented")
}
func (UnimplementedLikesServer) mustEmbedUnimplementedLikesServer() {}

// UnsafeLikesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikesServer will
// result in compilation errors.
type UnsafeLikesServer interface {
	mustEmbedUnimplementedLikesServer()
}

func RegisterLikesServer(s grpc.ServiceRegistrar, srv LikesServer) {
	s.RegisterService(&Likes_ServiceDesc, srv)
}

func _Likes_CreateLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServer).CreateLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Likes_CreateLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServer).CreateLikes(ctx, req.(*LikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Likes_GetLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikesServer).GetLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Likes_GetLikes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikesServer).GetLikes(ctx, req.(*GetLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Likes_ServiceDesc is the grpc.ServiceDesc for Likes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Likes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Likes",
	HandlerType: (*LikesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLikes",
			Handler:    _Likes_CreateLikes_Handler,
		},
		{
			MethodName: "GetLikes",
			Handler:    _Likes_GetLikes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "likes/likes.proto",
}
